### ISSUE TITLE
HUB and CtrlMainMenu

### ISSUE THREAD

**Issue by xfh** [studer-raimann/Hub#7]
When you activate the hub plugin in combination with the CtrlMainMenu plugin, a new menu entry for the hub is created, but it has no text nor link associated with it, so that you can't navigate to the hub GUI.

Furthermore, in the list of CtrlMainMenu's menu entries, a new last entry exists with title HUB and type Ctrl, but it provides no actions and saving the order fails with an exception because of an attempt to call setPosition() on a NULL object (ilCtrlMainMenuConfigGUI.php line 179).

I tested the combination of CtrlMainMenu 2.4 and Hub 1.1.14

**Comment by srgitlab** [comment]
Moved to Jira system
